pipelineName: docs-merge-pipeline 
repo: pingcap/docs
defaultRef: master 
triggers:
  push:
      onBranch:
      - "master"
      - "release-*"
tasks:
    - taskName: "docs-build-pdf" 
      checkerName: "common-check" 
      params:  
        shellScript: |
          sudo pip3 install boto3
          sudo pip3 install awscli
          printf "%s\n" ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY} ${AWS_REGION} "json" | aws configure
          grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok
          python3 scripts/merge_by_toc.py
          scripts/generate_pdf.sh
          sudo bash -c 'echo "222.222.95.49 uc.qbox.me" >> /etc/hosts';
          if [ "${TARGET_BRANCH}" = "master" ]; then
            python3 scripts/upload.py output.pdf tidb-dev-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-5.3" ]; then
            python3 scripts/upload.py output.pdf tidb-stable-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-5.2" ]; then
            python3 scripts/upload.py output.pdf tidb-v5.2-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-5.1" ]; then
            python3 scripts/upload.py output.pdf tidb-v5.1-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-5.0" ]; then
            python3 scripts/upload.py output.pdf tidb-v5.0-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-4.0" ]; then
            python3 scripts/upload.py output.pdf tidb-v4.0-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-3.1" ]; then
            python3 scripts/upload.py output.pdf tidb-v3.1-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-3.0" ]; then
            python3 scripts/upload.py output.pdf tidb-v3.0-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-2.1" ]; then
            python3 scripts/upload.py output.pdf tidb-v2.1-en-manual.pdf;
          fi
      credentials:
        - jenkinsID: docs-cn-aws-ak
          key: AWS_ACCESS_KEY
        - jenkinsID: docs-cn-aws-sk
          key: AWS_SECRET_KEY
        - jenkinsID: docs-cn-aws-region
          key: AWS_REGION
        - jenkinsID: docs-cn-aws-bn
          key: AWS_BUCKET_NAME
        - jenkinsID: docs-cn-qiniu-ak
          key: QINIU_ACCESS_KEY
        - jenkinsID: docs-cn-qiniu-sk
          key: QINIU_SECRET_KEY
        - jenkinsID: docs-cn-qiniu-bn
          key: QINIU_BUCKET_NAME
      image: "hub.pingcap.net/jenkins/docs-cn-checker:v0.0.1"
      resources:  
          requests:
              memory: "1000Mi"
              cpu: "500m"
          limits:
              memory: "2000Mi"
              cpu: "1000m"
